<?php

namespace Database\Seeders;

use App\Models\Cohort;
use App\Models\Course;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CohortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // ID:1 name:Birmingham
        // ID:2 name:Leicester
        // ID:3 name:Nottingham
        // ID:4 name:London
        // ID:5 name:Manchester

        // ye course oor id hai

        // ID:1	    name: SIA Door Supervisor
        // ID:2	    name: Door Supervisor Refresher
        // ID:3	    name: SIA CCTV Operator
        // ID:4	    name: security Guard Refresher
        // ID:5	    name: Level 1 Health and Safety Awareness within Construction Environment
        // ID:6	    name: Health and Safety Awareness - HSA
        // ID:7	    name: SSSTS – Site Supervision Safety
        // ID:8	    name: SSSTS Refresher
        // ID:9	    name: SMSTS – Site Management Safety
        // ID:10	name: SMSTS Refresher
        // ID:11	name: First Aid at Work
        // ID:12	name: Emergency First Aid at Work
        // ID:13	name: Paediatric First Aid Training Course
        // ID:14	name: TRAFFIC MARSHALL TRAININING
        // ID:15	name: FIRE SAFETY FOR FIRE WARDENS
        // ID:16	name: APHL Persolanal Licence
        // $cohorts = Cohort::factory()->count(100)->create();

        $cohorts = [

            // SIA Door Supervisor
            [
                'course_id' => 1,
                'venue_id' => 2, // Leicester
                'start_date_time' => Carbon::create(2025, 4, 29, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 5, 4, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'course_id' => 1,
                'venue_id' => 1, // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 19, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 5, 4, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 1,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'course_id' => 1,
                'venue_id' => 3, // Nottingham
                'start_date_time' => Carbon::create(2025, 4, 29, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 5, 4, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // CCTV Operator

            [
                'course_id' => 3,
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 28, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 30, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Door Supervisor Refresher April 2025
            [
                'course_id' => 2,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 8, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 9, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 12, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 13, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 14, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 15, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 19, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 20, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 24, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 25, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 29, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 30, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2, // Door Supervisor Refresher
                'venue_id' => 2,  // Leicester
                'start_date_time' => Carbon::create(2025, 4, 19, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 20, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2, // Door Supervisor Refresher
                'venue_id' => 5,  // Manchester
                'start_date_time' => Carbon::create(2025, 4, 15, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 16, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 5,  // Manchester
                'start_date_time' => Carbon::create(2025, 4, 26, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 27, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 3,  // Nottingham
                'start_date_time' => Carbon::create(2025, 4, 26, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 27, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'venue_id' => 3,  // Nottingham
                'start_date_time' => Carbon::create(2025, 4, 8, 13, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 9, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => json_encode([
                    'second_start_time' => '09:00',
                    'second_end_time' => '17:30',
                ]),
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Security Guard Refresher
            [
                'course_id' => 4,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 7, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 11, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 11, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 17, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 17, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 23, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 23, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 28, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 28, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4, // Security Guard Refresher
                'venue_id' => 2,  // Leicester
                'start_date_time' => Carbon::create(2025, 4, 7, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 2,
                'start_date_time' => Carbon::create(2025, 4, 28, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 28, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 5,  // Manchester
                'start_date_time' => Carbon::create(2025, 4, 7, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 5,
                'start_date_time' => Carbon::create(2025, 4, 14, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 14, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 5,
                'start_date_time' => Carbon::create(2025, 4, 25, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 25, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 3,  // Nottingham
                'start_date_time' => Carbon::create(2025, 4, 7, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 3,
                'start_date_time' => Carbon::create(2025, 4, 25, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 25, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'venue_id' => 3,
                'start_date_time' => Carbon::create(2025, 4, 28, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 28, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Emergency First Aid at Work

            [
                'course_id' => 12, // Emergency First Aid at Work
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 17, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 17, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12, // Emergency First Aid at Work
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 17, 13, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 17, 17, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 4, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 4, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 7, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 8, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 8, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 11, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 11, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 12, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 12, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 14, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 14, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 19, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 19, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 23, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 23, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 24, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 24, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 28, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 28, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 29, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 29, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 2,
                'start_date_time' => Carbon::create(2025, 4, 7, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 2,
                'start_date_time' => Carbon::create(2025, 4, 19, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 19, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 2,
                'start_date_time' => Carbon::create(2025, 4, 28, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 28, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 5,  // Manchester
                'start_date_time' => Carbon::create(2025, 4, 7, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 5,
                'start_date_time' => Carbon::create(2025, 4, 14, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 14, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 5,
                'start_date_time' => Carbon::create(2025, 4, 25, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 25, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 5,
                'start_date_time' => Carbon::create(2025, 4, 26, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 26, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 3,  // Nottingham
                'start_date_time' => Carbon::create(2025, 4, 7, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 3,
                'start_date_time' => Carbon::create(2025, 4, 8, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 8, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 3,
                'start_date_time' => Carbon::create(2025, 4, 25, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 25, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 3,
                'start_date_time' => Carbon::create(2025, 4, 26, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 26, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'venue_id' => 3,
                'start_date_time' => Carbon::create(2025, 4, 28, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 28, 13, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //  Traffic Marshal Training
            [
                'course_id' => 14, // Traffic Marshal Training
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 3, 31, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 3, 31, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14, // Traffic Marshal Training
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 4, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 4, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 7, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 11, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 11, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 16, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 16, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 23, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 23, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 26, 14, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 26, 16, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14, // Traffic Marshal Training
                'venue_id' => 5,   // Manchester
                'start_date_time' => Carbon::create(2025, 4, 16, 17, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 16, 19, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'venue_id' => 3,   // Nottingham
                'start_date_time' => Carbon::create(2025, 4, 9, 17, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 9, 19, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Health and Safety Awareness - HSA


            [
                'course_id' => 6,
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 5, 9, 0, 0),
                'end_date_time' => Carbon::create(2025, 4, 5, 17, 0, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Level 1 Health and Safety Awareness within Construction Environment

            [
                'course_id' => 5, // Level 1 Health and Safety Awareness within Construction Environment
                'venue_id' => 1,  // Birmingham
                'start_date_time' => Carbon::create(2025, 4, 4, 9, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 4, 10, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 7, 9, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 7, 10, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 11, 9, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 11, 10, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 16, 16, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 16, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 23, 16, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 23, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 1,
                'start_date_time' => Carbon::create(2025, 4, 26, 16, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 26, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 2,  // Leicester
                'start_date_time' => Carbon::create(2025, 4, 13, 16, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 13, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'venue_id' => 5,  // Manchester
                'start_date_time' => Carbon::create(2025, 4, 13, 16, 30, 0),
                'end_date_time' => Carbon::create(2025, 4, 13, 17, 30, 0),
                'max_learner' => 25,
                'status' => 'Confirmed',
                'additional_times' => null,
                'is_weekend' => 0,
                'is_soldout' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Add trainer_id to all cohorts
        $trainerId = 7;
        $cohorts = array_map(function ($cohort) use ($trainerId) {
            $cohort['trainer_id'] = $trainerId;
            return $cohort;
        }, $cohorts);


        DB::table('cohorts')->insert($cohorts);
    }
}
